name: kasir_flutter_app
description: A clean-structured Flutter POS (Kasir) app scaffold.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  google_fonts: ^6.2.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.9.0
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.4
  firebase_storage: ^13.0.0
  http: ^1.1.0
  fl_chart: ^1.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true