// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYfU1KCI9HUSyPnHw9wuMWhulc5Wl5S1M',
    appId: '1:382412040228:web:9352d93f021d1c632c90b1',
    messagingSenderId: '382412040228',
    projectId: 'farmasi-kasir',
    authDomain: 'farmasi-kasir.firebaseapp.com',
    storageBucket: 'farmasi-kasir.firebasestorage.app',
    measurementId: 'G-9BGBCPWGZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUkfdjiH3mQHJULKr0V0kIGVgOgVlkX_M',
    appId: '1:382412040228:android:aba5ddfaee5bebe72c90b1',
    messagingSenderId: '382412040228',
    projectId: 'farmasi-kasir',
    storageBucket: 'farmasi-kasir.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7eVu5M3AVmHwQF4L8hHV8toBHWWL7zMk',
    appId: '1:382412040228:ios:9e2b63ce9f1489742c90b1',
    messagingSenderId: '382412040228',
    projectId: 'farmasi-kasir',
    storageBucket: 'farmasi-kasir.firebasestorage.app',
    iosBundleId: 'com.example.kasirFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYfU1KCI9HUSyPnHw9wuMWhulc5Wl5S1M',
    appId: '1:382412040228:web:182274de18075eba2c90b1',
    messagingSenderId: '382412040228',
    projectId: 'farmasi-kasir',
    authDomain: 'farmasi-kasir.firebaseapp.com',
    storageBucket: 'farmasi-kasir.firebasestorage.app',
    measurementId: 'G-577Z2MRHHM',
  );
}
